### ISSUE TITLE
A vueltas con transiciones & transformaciones CSS

### ISSUE THREAD

**Issue by javiervelezreyes** [nucliweb/ama#5]
Estoy haciendo una serie de labs de ejemplo para ilustrar el funcionamiento de un framework Js que ando desarrollando desde hace tiempo y, para hacerlo amable y visual, trabajo con CSS. Sin embargo tengo un problema que no sé resolver. Te resumo lo que pretendo hacer y el resultado obtenido:

Imagina que implementamos 3 efectos visuales en css:
```
.lean-on { ... }   .lean-off { ... }  // inclinar
.min-on  { ... }   .min-off  { ... }  // alejar
.zoom-on { ... }   .zoom-off { ... }  // acercar
```

Para todos ellos utilizo transformaciones y transiciones:

```
.lean-on {
  transform  : perspective(2000px) rotateY(50deg) translateX(-200px) scale(1);
  transition : transform 0.3s linear;
}

.lean-off {
  transition : all 0.3s linear;
}

.min-on {
  transform        : scale(0.5);
  transform-origin : 0 0;
  transition       : transform 0.3s linear;
}

.min-off {
  transition : all 0.3s linear;
}

.zoom-on {
  transform-origin : center;
  transform        : scale(2);
  transition       : transform 0.3s linear;
}

.zoom-off {
  transition : all 0.3s linear;
}
````
Ahora pretendo controlar la aplicación simultánea de los efectos a un div a través de la manipulación por JS del atributo class:

<div id="A" class="show-on lean-off min-on zoom-off">View</div>

Sin embargo, la aplicación de unos efectos parece invalidar la de los otros. Por ejemplo, si hago min-on + lean-on el efecto min lo hace pero el efecto lean no. Si ahora hago min-off, de repente el efecto lean se dispara. Y además de todo esto las transiciones sufren reajuste visuales repentinos que rompen la fluidez.

 ¿Sabes por qué puede ser esto? Gracias de antemano ;)

**Comment by nucliweb** [comment]
Hola Javier 👋🏼

Te expongo el problema y dos posibles soluciones.

# Problema

El problema está en la famosa **C** de **CSS**, la cascada. El navegador lee de arriba a abajo todas las reglas y propiedades CSS, cada propiedad o regla anula la anterior. En la documentación de la [MDN](https://developer.mozilla.org/en/docs/Web/CSS/Cascade) encontrarás información detallada.

## Optimización

> Eliminemos las propiedades CSS que no són necesarias aprovechando la cascada.

El elemento HTML al que quieres aplicar las animaciones tiene las classes `view show-on zoom-off min-off lean-off` *(he activado el **show-on** para ver lo que hacemos* 🤪 *)*

```
<div class="view show-on zoom-off min-off lean-off">View A</div>
```

Esto hace que el elemento del DOM tenga aplicadas la propiedad `transition` varias veces.

<img width="960" alt="1" src="https://user-images.githubusercontent.com/1307927/70458775-19a60400-1ab3-11ea-8bbd-04b0a5d51dd6.png">

Veo que en la clase `show-on` has definido que las transformaciones sólo apliquen a `opacity`, eso está bien para optimizar el cálculo de repintado en la página, pero no sirve de mucho si luego se le añaden más clases con el valor `all` para las transiciones.

Si en su lugar, añades `transition: all 0.3s linear;` a la clase `view`, lo tendrás aplicado al elemento y estará definido sólamente una vez.

```css
.view {
    margin: 100px auto;
    width: 50%;
    height: 400px;
    max-width: 600px;
    color: #EEE;
    background: #FFF;
    box-shadow: 5px 5px 30px #111;
    font-weight: 400;
    font-size: 72px;
    text-align: center;
    transition: all 0.3s linear; /* <--- nueva línea  */
}
```

## Casos en los que funcionan las transformaciones ✅

### ZOOM

Con **SZOOM** podemos ver que añade la clase `zoom-on` y aplica la transformación `transform: scale(2);`.

<img width="960" alt="2" src="https://user-images.githubusercontent.com/1307927/70459412-6b02c300-1ab4-11ea-9cf7-0eb03972419e.png">

### LEAN

Con **SLEAN** podemos ver que añade la clase `lean-on` y aplica la transformación `transform: perspective(2000px) rotateY(50deg) translateX(-200px) scale(1);`.

<img width="960" alt="3" src="https://user-images.githubusercontent.com/1307927/70459548-ae5d3180-1ab4-11ea-9099-cfe275c22a03.png">

### MIN

Con **SMIN** podemos ver que añade la clase `min-on` y aplica la transformación `transform: scale(0.5);`.


## Casos en los que NO funcionan las transformaciones ❌

Tu intención es poder aplicar varias transformaciones al elemento, pero esto es lo que pasa cuando activamos **SLEAN** y **SMIN**.

<img width="960" alt="5" src="https://user-images.githubusercontent.com/1307927/70464484-419b6480-1abf-11ea-9450-9ce017511210.png">

Sólo se está aplicando la transformación de **SMIN**, ya que por el efecto cascada se está interpretando el `transform` de la clase `lean-on`:

```css
.lean-on {
    transform: perspective(2000px) rotateY(50deg) translateX(-200px) scale(1);
    transition: transform 0.3s linear;
}
```

Y seguidamente con la clase `min-on` se está sobreescribiendo con:

```css
.min-on {
    transform: scale(0.5);
    transform-origin: 0 0;
    transition: transform 0.3s linear;
}
```

El efecto deseado sería el siguiente:

<img width="960" alt="6" src="https://user-images.githubusercontent.com/1307927/70464955-3432aa00-1ac0-11ea-9b27-470d969b1979.png">

Donde si te fijas he modificado el valor de `transform` para que tenga los valores de las dos propiedades:

```css
.min-on {
    transform: scale(0.5) perspective(2000px) 
               rotateY(50deg) translateX(-200px) scale(1);
    transform-origin: 0 0;
    transition: transform 0.3s linear;
}
```


# Solución CSS

Como hemos visto que el problema lo tenemos al sobreescribir la propiedad `transform`, vamos a ver cómo podemos solucionarlo con [matrix3d](https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/matrix3d), uno de esos valores de transform y un gran desconocido.

Es una propiedad que por lo general la veremos aplicada mediante frameworks... mucho frameworks Javascript de animaciones hacen el cálculo para generar la matriz de transformación y poder aplicárserla con la función `matrix3d()`.

Lo curioso es que en el ejemplo anterior, si miramos en la pestaña **Computed** del DevTools de Chrome, veremos que realmente Chrome está aplicando la matriz 🤯.

<img width="960" alt="7" src="https://user-images.githubusercontent.com/1307927/70477458-348b6f00-1ad9-11ea-90e1-5998c297c032.png">

Si abrimos lo suficiente la pestaña, podremos ver, seleccionar y copiar el valor de la función **matrix3d()** para poder utilizarlo en nuestro CSS.

<img width="1094" alt="8" src="https://user-images.githubusercontent.com/1307927/70477929-399cee00-1ada-11ea-9350-8fcbbfbdd197.png">

Con este código definimos el selector CSS para que aplique cuando el elemento del DOM tenga las dos clases, así como la transformación con el nuevo valor.

```css
.lean-on.min-on {
  ...
  transform: matrix3d(0.321394, 0, -0.766044,
            0.000383022, 0, 0.5, 0, 0, 0.383022,
            0, 0.642788, -0.000321394, -64.2788,
            0, 153.209, 0.923396);
}
```

Esta solución nos puede funcionar bien con 3 o 4 clases para combinar, pero no está claro que no es escalable.

# Solución JS

Veamos cómo poder afrontar la solución desde Javascript, en este caso con [WAAPI](https://developer.mozilla.org/en-US/docs/Web/API/Web_Animations_API) *(Web Animation API)*. Si haces memoria, seguro que recuerdas que di una charla sobre WAAPI en [Codemotion 2017](https://slides.com/joanleon/waapi-codemotion#/).

Esta API nos permite definir y controlar las animaciones de forma programática 🤘🏼

Para lo que te interesa hacer, deberías concatenar las animaciones con [Effect composition](https://drafts.csswg.org/web-animations/#effect-composition), puedes revisar este extenso artículo en [CSS Tricks](https://css-tricks.com/additive-animation-web-animations-api/).

Tendrás que tener en cuenta el soporte de WAAPI en los navegadores, pero tienes disponible un [polyfill](https://github.com/animationatwork/web-animate) para dar soporte a esta nueva API.

----

Espero haberte ayudado con tu consulta, un abrazo.

**Comment by nucliweb** [comment]
Por cierto @javiervelezreyes, con este código puedes obtener las tranformaciones convertidas a **matrix3d()** en Google Chrome.

```
getComputedStyle(document.querySelector('.view')).transform
```
Esto te devolverá:

```
"matrix3d(0.642788, 0, -0.766044, 0.000383022, 0, 1, 0, 0, 0.766044, 0, 0.642788, -0.000321394, -128.558, 0, 153.209, 0.923396)"
```

También tienes esta librería [Rematrix](https://github.com/jlmakes/rematrix), que te ayudará a automatixar los cálculos.

**Comment by elrumordelaluz** [comment]
Aqui hos dejo un pequeño aporte. [TLDR](https://codepen.io/elrumordelaluz/pen/367611732c89df78fd7777ff5bd37a9c?editors=0100)

**C**onsiderando que siempre vamos a tener que lidiar con aquella **C** de _CSS_. 

Aquella _cascada_ que en la mayoría de los casos la veneramos y nos es súper útil. Y aquella _casacada_  que solo en algunas situaciones nos pone en `!dificultad` y nos lamentamos (de todas formas creo que estos casos son casi siempre por solicitarle al _CSS_ algo que excede su misión en este planeta).

Volviendo, este pequeño aporte tiene que tener en cuenta la cascada, o bien cómo se ordenan la clases en la hoja de estilos. De este modo podremos elegir cuál clase priorizar en el caso que tenga que aplicar la misma tranformación (scale, translate, rotate…).

Haremos uso de las grandiosas [Custom Properties](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties) (conocidas en el barrio como _CSS Variables) que nos permitirán de definir la transformación en cada una de sus partes.

Comenzamos aplicando una gran transformación, con valores que no transforman, los valores _default_ de las variables:

```css
.elem {
  --x: 0;
  --y: 0;
  --scale: 1;
  --rot-x: 0deg;
  --rot-y: 0deg;
  --perspective: 0;

  transform: 
    perspective(var(--perspective))
    translateX(var(--x)) 
    translateY(var(--y)) 
    scale(var(--scale)) 
    rotateX(var(--rot-x))
    rotateY(var(--rot-y))
}
```

Y luego creamos las clases de cada _efecto_, algo así como:
```css
.lean {
  --perspective: 2000px;
  --rot-y: 50deg;
  --x: -200px;
  --scale: 1;
}

.min {
  --scale: .5;
}

.zoom {
  --scale: 2;
}
```

Y aquí es donde juega un rol importante la cascada. Apareciendo `.zoom` después de `.min` y modificando la misma propiedad de transformación, va a tener prioridad `.zoom`. Aquí la toma de decisión de quien escribe el código.

Aquí os dejo el [pen](https://codepen.io/elrumordelaluz/pen/367611732c89df78fd7777ff5bd37a9c?editors=0100) ejemplificando esta idea. A considerar que se pueden agregar las transformaciones que faltan en la declaración `transform: …`. Aquí hay otro punto de opinión de parte del autor del _CSS_ ya que _el orden de los factores —[transform values](https://developer.mozilla.org/en-US/docs/Web/CSS/transform)— altera el producto_:

> The transform functions are multiplied in order from left to right, meaning that composite transforms are effectively applied in order from right to left.

Espero sea de utilidad, tanto concretamente para la _issue_ abierta, como para que sigamos aprendiendo usos y abusos de las _CSS Custom Properties_ que me parece son infinitos y de CSS en general
